name: Terraform VPC

on:
  push:
    branches: [ main ]
    paths:
      - "AWS-VPC/**"

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    # 🔒 THIS ENABLES MANUAL APPROVAL
    environment: terraform-prod

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: AWS-VPC

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::216890067432:role/GitHub
        
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 🚀 APPLY (auto-approve, but approval comes from GitHub UI)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
